### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mpcom** [yetanotherx/WorldEditCUI#1]
Hi,

does not work for me.

Minecraft 1.0

Server Info:

> version 
> 11:36:37 [INFORMATION] This server is running Craftbukkit version git-Bukkit-1.8.1-R4-77-ge86a355-b1550jnks (MC: 1.0.1) (Implementing API version 1.0.0-R1-SNAPSHOT)
> version WorldEdit
> 11:36:39 [INFORMATION] WorldEdit version 596-4753574

**Comment by yetanotherx** [comment]
That's because I haven't fionished yet. You're running a dev build.
