### ISSUE TITLE
//TODO Settings doesn't work?

### ISSUE THREAD

**Issue by ScoreUnder** [yetanotherx/WorldEditCUI#2]
Warning, this may induce varying degrees of facepalm:

new File(this.propertiesFile.getParent()).mkdirs();

**Comment by ScoreUnder** [comment]
(If that was a little too plain, I meant you were missing that line of code and just creating the config file regardless of whether it actually has a place to exist)

**Comment by yetanotherx** [comment]
Nope, that's not the issue. The config file works as expected, it's an issue with KeyBinding instead.
