### ISSUE TITLE
ModLoader abandoned

### ISSUE THREAD

**Issue by bitfed** [yetanotherx/WorldEditCUI#7]
I know you are waiting for the API, but for many people who use mods, throwing ModLoader out the window is the same as not updating at all.

**Comment by yetanotherx** [comment]
I have no control over this issue. This is between Zombe and Tanzanite.

**Comment by bitfed** [comment]
I wasn't expecting a jump in activity because of my comment:  Especially considering that Modloader being 'too hard' caused what basically amounts to this mod being abandoned until the professional Bukkit/Mojang coders make this projects team an API to use.

As the situation currently stands, it _appears_ maintained, when in reality, it's broken.

This is an essential tool for server administration and there is NO release date for the API.  Bukkit has been hired to do the API, but has only been on staff for 8 days and have made zero announcements about the timescale of the API.

This mod is effectively 'broken', perhaps you should label it as 'On Hold' so the community actually knows what's going on, and can patch it?

**Comment by bitfed** [comment]
I've looked it up though and people have said a couple things.  Someone said on your thread that Modloader has been fixed, and also someone posted a fix for Zombe's modloader bug on Zombe's modpack thread.  

A third party confirmed that this fix worked 'perfectly', though I'm not sure if it's relevant to your problems.  I'm afraid I'm at a disadvantage because I don't get the relationship between this mod, Modloader, and Zombe/Tanzanite

I had read a developers comment, which I can no longer find, that said "Modloader is causing too many problems, removed".  The fact is that this mod does not play nice with other mods on its own.

You say you have no control, but you are the one publishing this and not marking it as broken, which it effectively is.  Someone would probably able to patch it if this issue was made a little more transparent.

Waiting for the API is waiting for a tomorrow that keeps moving farther and farther away.  Please seek help with this, for the sake of your userbase and their admin woes.

**Comment by md-5** [comment]
I have no idea what this is about...

**Comment by yetanotherx** [comment]
I am _so_ confused right now. I don't think you know what you are talking about. ModLoader is not abandoned. WorldEditCUI is not abandoned. They work perfectly fine together. Nothing is broken.

**Comment by bitfed** [comment]
Sorry, I meant to be specific.  I meant the /Mod folder loading of Modloader.

This mod doesn't play nice with other mods when put inside the minecraft.jar.
